name: CICD pipeline

on:
  push:
    branches: [ 'main' ]

jobs: 
  compile:
    runs-on: ubuntu-latest

    steps:  # <-- This must be indented under the job
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile
